---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install --save-dev surge
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install

after_success:
  - ember surge --environment development

script:
  - npm test
