---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install --save-dev surge
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install

after_success:
  - make actualizar_web

after_success:
  - test $TRAVIS_BRANCH = "develop" && ./node_modules/ember-cli/bin/ember surge --environment development --new-domain develop-pilas-bloques-jr.surge.sh
  - test $TRAVIS_BRANCH = "master" &&  ./node_modules/ember-cli/bin/ember surge --environment development --new-domain pilas-bloques-jr.surge.sh

script:
  - make test_travis
